export const defaultBooks = [
  {
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    price: 1000,
    image: "images/books/to-kill-a-mockingbird.webp",
    rating: {
      stars: 5,
      reviews: 1203,
    },
    discount: 15,
    genre: ["Historical Fiction"],
    copiesSold: 2500,
    description:
      "Set in the racially charged American South of the 1930s, To Kill a Mockingbird follows young Scout Finch as she grows up witnessing her father, Atticus Finch, defend a Black man falsely accused of a crime. Through Scout\u2019s innocent eyes, the novel explores themes of justice, morality, and compassion in a divided society. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quo porro excepturi doloribus dolorem dignissimos minus incidunt vel labore tempora commodi, quae ullam maxime expedita aspernatur totam possimus temporibus magni eum.Nihil laudantium voluptatum facere, voluptatem, nam illo harum dolorem repudiandae aut libero officiis! Quae ipsam nisi amet eius culpa magnam blanditiis labore sunt, tempore aliquid ad harum quam unde consequatur?",
    publishedYear: 1960,
    keywords: [
      "classic",
      "racism",
      "justice",
      "coming-of-age",
      "Harper Lee",
      "Atticus Finch",
      "Scout Finch",
      "Tom Robinson",
      "Great Depression",
      "Alabama",
      "1930s",
      "racial injustice",
      "courtroom drama",
      "moral growth",
      "Southern Gothic",
      "prejudice",
      "innocence",
      "historical fiction",
      "social inequality",
      "American literature",
      "empathy",
      "child narrator",
      "civil rights",
      "mockingbird metaphor",
      "Pulitzer Prize",
    ],
  },
  {
    title: "1984",
    author: "George Orwell",
    price: 900,
    image: "images/books/ninety-eight-four.jpg",
    rating: {
      stars: 4.5,
      reviews: 811,
    },
    genre: ["Dystopian Fiction"],
    copiesSold: 3000,
    description:
      "Set in a totalitarian society ruled by the Party and its omnipresent leader, Big Brother, “1984” follows Winston Smith as he secretly rebels against oppressive control, surveillance, and the distortion of truth. It's a chilling portrayal of a future where independent thought is a crime. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quo porro excepturi doloribus dolorem dignissimos minus incidunt vel labore tempora commodi, quae ullam maxime expedita aspernatur totam possimus temporibus magni eum.Nihil laudantium voluptatum facere, voluptatem, nam illo harum dolorem repudiandae aut libero officiis! Quae ipsam nisi amet eius culpa magnam blanditiis labore sunt, tempore aliquid ad harum quam unde consequatur?",
    publishedYear: 1949,
    keywords: [
      "dystopia",
      "totalitarianism",
      "surveillance",
      "freedom",
      "George Orwell",
      "Winston Smith",
      "Big Brother",
      "Thought Police",
      "Newspeak",
      "Room 101",
      "doublethink",
      "thoughtcrime",
      "telescreen",
      "ministry of truth",
      "oppression",
      "dictatorship",
      "propaganda",
      "mind control",
      "repression",
      "Orwellian",
      "futuristic",
      "rebellion",
      "control",
      "individualism",
      "censorship",
      "classic",
      "British literature",
      "1984",
    ],
  },
  {
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    price: 1100,
    image: "images/books/the-great-gatsby.jpg",
    rating: {
      stars: 4.0,
      reviews: 672,
    },
    genre: ["Classic", "Literary Fiction"],
    copiesSold: 2700,
    description:
      "The Great Gatsby tells the story of Jay Gatsby, a mysterious millionaire known for his extravagant parties. Set in the Roaring Twenties, the novel explores Gatsby\u2019s obsessive love for Daisy Buchanan and critiques the American Dream, revealing the emptiness beneath wealth and glamour. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quo porro excepturi doloribus dolorem dignissimos minus incidunt vel labore tempora commodi, quae ullam maxime expedita aspernatur totam possimus temporibus magni eum.Nihil laudantium voluptatum facere, voluptatem, nam illo harum dolorem repudiandae aut libero officiis! Quae ipsam nisi amet eius culpa magnam blanditiis labore sunt, tempore aliquid ad harum quam unde consequatur?",
    publishedYear: 1925,
    keywords: [
      "American Dream",
      "wealth",
      "love",
      "tragedy",
      "F. Scott Fitzgerald",
      "Jay Gatsby",
      "Daisy Buchanan",
      "Nick Carraway",
      "Roaring Twenties",
      "1920s",
      "East Egg",
      "West Egg",
      "Long Island",
      "parties",
      "obsession",
      "lost love",
      "social class",
      "greed",
      "illusion",
      "flappers",
      "jazz age",
      "classic",
      "literary fiction",
      "affair",
      "bootlegging",
      "symbolism",
      "green light",
      "Valley of Ashes",
      "materialism",
      "Gatsby",
    ],
  },
  {
    title: "Pride and Prejudice",
    author: "Jane Austen",
    price: 950,
    image: "images/books/pride-and-prejudice.jpeg",
    rating: {
      stars: 4.5,
      reviews: 1529,
    },
    genre: ["Classic", "Romance"],
    copiesSold: 2000,
    description:
      "Pride and Prejudice is a timeless novel by Jane Austen that explores themes of love, social class, and misunderstandings. It follows Elizabeth Bennet as she navigates the complexities of manners, upbringing, and marriage in early 19th-century England, ultimately discovering love and personal growth. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quo porro excepturi doloribus dolorem dignissimos minus incidunt vel labore tempora commodi, quae ullam maxime expedita aspernatur totam possimus temporibus magni eum.Nihil laudantium voluptatum facere, voluptatem, nam illo harum dolorem repudiandae aut libero officiis! Quae ipsam nisi amet eius culpa magnam blanditiis labore sunt, tempore aliquid ad harum quam unde consequatur?",
    publishedYear: 1813,
    keywords: [
      "Jane Austen",
      "Pride and Prejudice",
      "Elizabeth Bennet",
      "Mr. Darcy",
      "romance",
      "marriage",
      "society",
      "class",
      "19th century",
      "Regency era",
      "family",
      "social status",
      "love",
      "prejudice",
      "pride",
      "witty",
      "courtship",
      "English literature",
      "novel",
      "character development",
      "wealth",
      "rural England",
      "Bennet family",
      "dance",
      "ball",
      "matchmaking",
      "comedy",
      "women's roles",
      "morality",
      "romantic tension",
    ],
  },
  {
    title: "The Catcher in the Rye",
    author: "J.D. Salinger",
    price: 1050,
    image: "images/books/the-catcher-in-the-rye.jpeg",
    rating: {
      stars: 4.0,
      reviews: 700,
    },
    genre: ["Classic", "Coming-of-Age"],
    copiesSold: 650,
    description:
      "The Catcher in the Rye by J.D. Salinger is a classic novel that captures the teenage angst and alienation of Holden Caulfield, a disillusioned teenager wandering New York City after being expelled from school. It explores themes of identity, innocence, and the challenges of growing up. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quo porro excepturi doloribus dolorem dignissimos minus incidunt vel labore tempora commodi, quae ullam maxime expedita aspernatur totam possimus temporibus magni eum.Nihil laudantium voluptatum facere, voluptatem, nam illo harum dolorem repudiandae aut libero officiis! Quae ipsam nisi amet eius culpa magnam blanditiis labore sunt, tempore aliquid ad harum quam unde consequatur?",
    publishedYear: 1951,
    keywords: [
      "J.D. Salinger",
      "The Catcher in the Rye",
      "Holden Caulfield",
      "coming-of-age",
      "teen angst",
      "alienation",
      "identity",
      "rebellion",
      "loss",
      "depression",
      "New York City",
      "mental health",
      "innocence",
      "phoniness",
      "narrative",
      "adolescence",
      "psychological",
      "classic",
      "post-war America",
      "search for meaning",
      "loneliness",
      "youth",
      "family",
      "society",
      "cynicism",
    ],
  },
  {
    title: "Moby-Dick",
    author: "Herman Melville",
    price: 1200,
    image: "images/books/moby-dick.jpg",
    rating: {
      stars: 4.5,
      reviews: 1789,
    },
    genre: ["Adventure"],
    copiesSold: 2200,
    description:
      "Moby Dick follows Captain Ahab\u2019s relentless pursuit of a giant white whale that once injured him. The novel explores themes of obsession, revenge, and the human spirit\u2019s fight against nature\u2019s power. It\u2019s a classic adventure with deep philosophical reflections. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quo porro excepturi doloribus dolorem dignissimos minus incidunt vel labore tempora commodi, quae ullam maxime expedita aspernatur totam possimus temporibus magni eum.Nihil laudantium voluptatum facere, voluptatem, nam illo harum dolorem repudiandae aut libero officiis! Quae ipsam nisi amet eius culpa magnam blanditiis labore sunt, tempore aliquid ad harum quam unde consequatur?",
    publishedYear: 1851,
    keywords: [
      "Herman Melville",
      "Moby-Dick",
      "Ahab",
      "Ishmael",
      "whaling",
      "sea adventure",
      "obsession",
      "revenge",
      "white whale",
      "nature",
      "fate",
      "madness",
      "man vs nature",
      "19th century",
      "classic literature",
      "voyage",
      "existentialism",
      "symbolism",
      "isolation",
      "maritime",
      "American literature",
      "philosophy",
      "tragedy",
      "narrative",
      "survival",
    ],
  },
  {
    title: "War and Peace",
    author: "Leo Tolstoy",
    price: 1500,
    image: "images/books/war-and-peace.jpg",
    rating: {
      stars: 5,
      reviews: 679,
    },
    genre: ["Historical Fiction", "Drama"],
    copiesSold: 3600,
    description:
      "War and Peace is an epic novel that tells the story of Russian society during the Napoleonic Wars. It weaves together the lives of aristocratic families, exploring love, war, fate, and the search for meaning amid chaos. It combines historical events with personal drama and philosophical insight. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quo porro excepturi doloribus dolorem dignissimos minus incidunt vel labore tempora commodi, quae ullam maxime expedita aspernatur totam possimus temporibus magni eum.Nihil laudantium voluptatum facere, voluptatem, nam illo harum dolorem repudiandae aut libero officiis! Quae ipsam nisi amet eius culpa magnam blanditiis labore sunt, tempore aliquid ad harum quam unde consequatur?",
    publishedYear: 1869,
    keywords: [
      "Leo Tolstoy",
      "War and Peace",
      "Napoleonic Wars",
      "Russian aristocracy",
      "Pierre Bezukhov",
      "Andrei Bolkonsky",
      "Natasha Rostova",
      "history",
      "philosophy",
      "love",
      "war",
      "peace",
      "family",
      "society",
      "Russian literature",
      "19th century",
      "realism",
      "fate",
      "redemption",
      "growth",
      "power",
      "conflict",
      "epic",
      "Russian culture",
    ],
  },
  {
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    price: 980,
    image: "images/books/the-hobbit.jpg",
    rating: {
      stars: 4.5,
      reviews: 978,
    },
    discount: 10,
    genre: ["Fantasy", "Adventure"],
    copiesSold: 1500,
    description:
      "Bilbo Baggins, a peaceful hobbit, is swept into an epic adventure with a group of dwarves seeking to reclaim their homeland from the dragon Smaug. Along the journey, Bilbo encounters magical creatures, overcomes unexpected dangers, and discovers his own bravery and resourcefulness. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quo porro excepturi doloribus dolorem dignissimos minus incidunt vel labore tempora commodi, quae ullam maxime expedita aspernatur totam possimus temporibus magni eum.Nihil laudantium voluptatum facere, voluptatem, nam illo harum dolorem repudiandae aut libero officiis! Quae ipsam nisi amet eius culpa magnam blanditiis labore sunt, tempore aliquid ad harum quam unde consequatur?",
    publishedYear: 1937,
    keywords: [
      "J.R.R. Tolkien",
      "The Hobbit",
      "Bilbo Baggins",
      "Middle-earth",
      "adventure",
      "dragon",
      "Smaug",
      "quest",
      "fantasy",
      "dwarves",
      "elves",
      "magic",
      "courage",
      "friendship",
      "treasure",
      "journey",
      "hobbit",
      "mythology",
      "heroism",
      "epic",
      "legend",
      "darkness",
      "light",
      "ring",
    ],
  },
  {
    title: "Brave New World",
    author: "Aldous Huxley",
    price: 970,
    image: "images/books/brave-new-world.jpg",
    rating: {
      stars: 5.0,
      reviews: 1457,
    },
    genre: ["Dystopian", "Science Fiction"],
    copiesSold: 2000,
    description:
      'In a futuristic society where happiness is engineered and individuality is suppressed, people live under strict control through technology and conditioning. The story follows Bernard Marx as he begins to question the cost of this "perfect" world and explores the consequences of sacrificing freedom for stability.Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quo porro excepturi doloribus dolorem dignissimos minus incidunt vel labore tempora commodi, quae ullam maxime expedita aspernatur totam possimus temporibus magni eum.Nihil laudantium voluptatum facere, voluptatem, nam illo harum dolorem repudiandae aut libero officiis! Quae ipsam nisi amet eius culpa magnam blanditiis labore sunt, tempore aliquid ad harum quam unde consequatur?',
    publishedYear: 1932,
    keywords: [
      "Aldous Huxley",
      "Brave New World",
      "dystopia",
      "totalitarianism",
      "science fiction",
      "genetic engineering",
      "social control",
      "consumerism",
      "technology",
      "conditioning",
      "utopia",
      "freedom",
      "identity",
      "society",
      "philosophy",
      "conformity",
      "happiness",
      "soma",
      "individualism",
      "rebellion",
      "future",
    ],
  },
  {
    title: "Crime and Punishment",
    author: "Fyodor Dostoevsky",
    price: 1150,
    image: "images/books/crime-and-punishment.jpg",
    rating: {
      stars: 5.0,
      reviews: 1966,
    },
    genre: ["Psychological"],
    copiesSold: 4000,
    description:
      "This novel follows Raskolnikov, a poor student in St. Petersburg, who commits a murder believing he can justify it for a greater good. As guilt and paranoia consume him, the story explores morality, redemption, and the depths of human conscience. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quo porro excepturi doloribus dolorem dignissimos minus incidunt vel labore tempora commodi, quae ullam maxime expedita aspernatur totam possimus temporibus magni eum.Nihil laudantium voluptatum facere, voluptatem, nam illo harum dolorem repudiandae aut libero officiis! Quae ipsam nisi amet eius culpa magnam blanditiis labore sunt, tempore aliquid ad harum quam unde consequatur?",
    publishedYear: 1866,
    keywords: [
      "Fyodor Dostoevsky",
      "Crime and Punishment",
      "psychological novel",
      "moral dilemmas",
      "guilt",
      "redemption",
      "poverty",
      "murder",
      "conscience",
      "suffering",
      "philosophy",
      "existentialism",
      "justice",
      "redemption",
      "urban life",
      "St. Petersburg",
      "alienation",
      "confession",
      "religion",
      "psychology",
    ],
  },
  {
    title: "Jane Eyre",
    author: "Charlotte Brontë",
    price: 990,
    image: "images/books/jane-eyre.jpg",
    rating: {
      stars: 4.0,
      reviews: 557,
    },
    genre: ["Gothic Romance", "Classic"],
    copiesSold: 1000,
    description:
      "Jane Eyre tells the story of an orphaned girl who grows into a strong, independent woman. She becomes a governess at Thornfield Hall, where she meets the mysterious Mr. Rochester. The novel explores themes of love, morality, and social class, with dark secrets adding suspense to the romance. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quo porro excepturi doloribus dolorem dignissimos minus incidunt vel labore tempora commodi, quae ullam maxime expedita aspernatur totam possimus temporibus magni eum.Nihil laudantium voluptatum facere, voluptatem, nam illo harum dolorem repudiandae aut libero officiis! Quae ipsam nisi amet eius culpa magnam blanditiis labore sunt, tempore aliquid ad harum quam unde consequatur?",
    publishedYear: 1847,
    keywords: [
      "Charlotte Brontë",
      "Jane Eyre",
      "gothic novel",
      "romance",
      "coming-of-age",
      "female independence",
      "morality",
      "social class",
      "love",
      "passion",
      "orphan",
      "mystery",
      "self-discovery",
      "empowerment",
      "dark secrets",
      "rebellion",
      "Victorian era",
      "identity",
      "resilience",
      "redemption",
    ],
  },
  {
    title: "The Alchemist",
    author: "Paulo Coelho",
    price: 890,
    image: "images/books/the-alchemist.jpeg",
    rating: {
      stars: 4.5,
      reviews: 2100,
    },
    discount: 11,
    genre: ["Adventure", "Fantasy"],
    copiesSold: 1700,
    description:
      "The Alchemist tells the story of Santiago, a shepherd who sets out to find a hidden treasure near the pyramids. His journey teaches him about following his dreams, trusting the universe, and discovering his true purpose in life. Along the way, he learns valuable lessons about love, destiny, and self-discovery. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quo porro excepturi doloribus dolorem dignissimos minus incidunt vel labore tempora commodi, quae ullam maxime expedita aspernatur totam possimus temporibus magni eum.Nihil laudantium voluptatum facere, voluptatem, nam illo harum dolorem repudiandae aut libero officiis! Quae ipsam nisi amet eius culpa magnam blanditiis labore sunt, tempore aliquid ad harum quam unde consequatur?",
    publishedYear: 1988,
    keywords: [
      "Paulo Coelho",
      "The Alchemist",
      "philosophical novel",
      "personal legend",
      "dreams",
      "self-discovery",
      "spiritual journey",
      "alchemy",
      "destiny",
      "omens",
      "love",
      "wisdom",
      "adventure",
      "hope",
      "transformation",
      "universe",
      "faith",
      "courage",
      "miracles",
      "quest",
    ],
  },
  {
    title: "The Lord of the Rings",
    author: "J.R.R. Tolkien",
    price: 1800,
    image: "images/books/the-lord-of-the-rings.jpg",
    rating: {
      stars: 5.0,
      reviews: 3500,
    },
    genre: ["Fantasy", "Adventure"],
    copiesSold: 13000,
    description:
      "The Lord of the Rings tells the story of Frodo Baggins, a hobbit who must destroy a powerful ring to stop dark forces from taking over Middle-earth. Joined by friends, he embarks on a dangerous journey full of battles, magic, and sacrifice, discovering courage and hope along the way. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quo porro excepturi doloribus dolorem dignissimos minus incidunt vel labore tempora commodi, quae ullam maxime expedita aspernatur totam possimus temporibus magni eum.Nihil laudantium voluptatum facere, voluptatem, nam illo harum dolorem repudiandae aut libero officiis! Quae ipsam nisi amet eius culpa magnam blanditiis labore sunt, tempore aliquid ad harum quam unde consequatur?",
    publishedYear: 1954,
    keywords: [
      "J.R.R. Tolkien",
      "The Lord of the Rings",
      "fantasy",
      "middle-earth",
      "hobbits",
      "quest",
      "ring",
      "dark lord",
      "friendship",
      "courage",
      "adventure",
      "epic",
      "magic",
      "battle",
      "evil",
      "hope",
      "fellowship",
      "mythology",
      "heroism",
      "journey",
    ],
  },
  {
    title: "The Book Thief",
    author: "Markus Zusak",
    price: 950,
    image: "images/books/the-book-thief.jpg",
    rating: {
      stars: 5.0,
      reviews: 1900,
    },
    genre: ["Historical Fiction"],
    copiesSold: 800,
    description:
      "The Book Thief tells the story of Liesel Meminger, a young girl living in Nazi Germany during World War II. As she navigates the hardships of war, Liesel finds solace in stealing books and sharing their stories with others. Through her growing love of words and reading, she forms meaningful friendships and learns about hope, courage, and the human spirit in the darkest of times. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quo porro excepturi doloribus dolorem dignissimos minus incidunt vel labore tempora commodi, quae ullam maxime expedita aspernatur totam possimus temporibus magni eum.Nihil laudantium voluptatum facere, voluptatem, nam illo harum dolorem repudiandae aut libero officiis! Quae ipsam nisi amet eius culpa magnam blanditiis labore sunt, tempore aliquid ad harum quam unde consequatur?",
    publishedYear: 2005,
    keywords: [
      "Markus Zusak",
      "The Book Thief",
      "historical fiction",
      "World War II",
      "Nazi Germany",
      "death narrator",
      "books",
      "friendship",
      "loss",
      "courage",
      "family",
      "war",
      "hope",
      "resilience",
      "young protagonist",
      "storytelling",
      "grief",
      "resistance",
      "literacy",
    ],
  },
  {
    title: "The Road",
    author: "Cormac McCarthy",
    price: 990,
    image: "images/books/the-road.jpg",
    rating: {
      stars: 4.0,
      reviews: 800,
    },
    discount: 15,
    genre: ["Post-Apocalyptic", "Drama"],
    copiesSold: 500,
    description:
      "The Road tells the harrowing journey of a father and his young son as they travel across a devastated, ash-covered America after an unspecified apocalypse. Struggling to survive amid scarce resources and constant danger, their bond and hope for humanity are tested. The story explores themes of love, survival, and the will to carry on in a bleak, unforgiving world. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quo porro excepturi doloribus dolorem dignissimos minus incidunt vel labore tempora commodi, quae ullam maxime expedita aspernatur totam possimus temporibus magni eum.Nihil laudantium voluptatum facere, voluptatem, nam illo harum dolorem repudiandae aut libero officiis! Quae ipsam nisi amet eius culpa magnam blanditiis labore sunt, tempore aliquid ad harum quam unde consequatur?",
    publishedYear: 2006,
    keywords: [
      "Cormac McCarthy",
      "The Road",
      "post-apocalyptic",
      "father and son",
      "survival",
      "desolation",
      "hope",
      "journey",
      "dark",
      "love",
      "humanity",
      "struggle",
      "end of the world",
      "gritty",
      "literary fiction",
      "emotional",
      "bond",
      "sacrifice",
      "nature",
      "loss",
    ],
  },
  {
    title: "Little Women",
    author: "Louisa May Alcott",
    price: 870,
    image: "images/books/little-women.jpg",
    rating: {
      stars: 4.5,
      reviews: 1600,
    },
    genre: ["Classic", "Coming-of-Age"],
    copiesSold: 1000,
    description:
      "Little Women follows the lives of the four March sisters, Meg, Jo, Beth, and Amy, as they grow up during the American Civil War. The novel explores their struggles, dreams, and close family bonds, highlighting themes of love, personal growth, and the challenges of womanhood in a changing society. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quo porro excepturi doloribus dolorem dignissimos minus incidunt vel labore tempora commodi, quae ullam maxime expedita aspernatur totam possimus temporibus magni eum.Nihil laudantium voluptatum facere, voluptatem, nam illo harum dolorem repudiandae aut libero officiis! Quae ipsam nisi amet eius culpa magnam blanditiis labore sunt, tempore aliquid ad harum quam unde consequatur?",
    publishedYear: 1868,
    keywords: [
      "Louisa May Alcott",
      "Little Women",
      "coming-of-age",
      "sisterhood",
      "family",
      "love",
      "growth",
      "19th century",
      "domestic life",
      "female empowerment",
      "marriage",
      "poverty",
      "hope",
      "resilience",
      "friendship",
      "moral values",
      "American classic",
      "literary fiction",
      "sisters",
      "winter",
    ],
  },
  {
    title: "Dracula",
    author: "Bram Stoker",
    price: 950,
    image: "images/books/dracula.jpg",
    rating: {
      stars: 4.0,
      reviews: 1340,
    },
    genre: ["Gothic", "Horror"],
    copiesSold: 1200,
    description:
      "Dracula tells the story of Count Dracula\u2019s attempt to move from Transylvania to England to spread his undead curse. Through a series of journal entries and letters, the novel follows Jonathan Harker, Mina Murray, and their allies as they confront the vampire\u2019s dark power. It explores themes of fear, superstition, and the battle between good and evil. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quo porro excepturi doloribus dolorem dignissimos minus incidunt vel labore tempora commodi, quae ullam maxime expedita aspernatur totam possimus temporibus magni eum.Nihil laudantium voluptatum facere, voluptatem, nam illo harum dolorem repudiandae aut libero officiis! Quae ipsam nisi amet eius culpa magnam blanditiis labore sunt, tempore aliquid ad harum quam unde consequatur?",
    publishedYear: 1897,
    keywords: [
      "Bram Stoker",
      "Dracula",
      "vampire",
      "gothic",
      "horror",
      "supernatural",
      "Transylvania",
      "vampirism",
      "fear",
      "darkness",
      "immortality",
      "19th century",
      "victorian",
      "mystery",
      "romance",
      "folklore",
      "hunter",
      "curse",
      "blood",
      "classic horror",
    ],
  },
  {
    title: "Frankenstein",
    author: "Mary Shelley",
    price: 920,
    image: "images/books/frankenstein.jpg",
    rating: {
      stars: 4.5,
      reviews: 1425,
    },
    discount: 8,
    genre: ["Science Fiction", "Horror"],
    copiesSold: 1000,
    description:
      "Frankenstein tells the story of Victor Frankenstein, a scientist who creates a living being from assembled body parts. The creature, rejected and shunned by society, struggles with loneliness and revenge. The novel explores themes of ambition, responsibility, and the consequences of playing God. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quo porro excepturi doloribus dolorem dignissimos minus incidunt vel labore tempora commodi, quae ullam maxime expedita aspernatur totam possimus temporibus magni eum.Nihil laudantium voluptatum facere, voluptatem, nam illo harum dolorem repudiandae aut libero officiis! Quae ipsam nisi amet eius culpa magnam blanditiis labore sunt, tempore aliquid ad harum quam unde consequatur?",
    publishedYear: 1818,
    keywords: [
      "Mary Shelley",
      "Frankenstein",
      "science fiction",
      "gothic",
      "horror",
      "monster",
      "creation",
      "nature vs nurture",
      "morality",
      "science",
      "ambition",
      "romanticism",
      "isolation",
      "tragedy",
      "19th century",
      "ethical dilemma",
      "mad scientist",
      "revenge",
      "existentialism",
      "classic literature",
    ],
  },
  {
    title: "Wuthering Heights",
    author: "Emily Brontë",
    price: 880,
    image: "images/books/wuthering-heights.jpg",
    rating: {
      stars: 4.0,
      reviews: 1200,
    },
    genre: ["Classic", "Gothic"],
    copiesSold: 500,
    description:
      "Wuthering Heights by Emily Brontë is a classic Gothic novel about intense, often destructive love and revenge between the passionate Heathcliff and Catherine Earnshaw. Set on the Yorkshire moors, the story explores themes of obsession, social class, and the supernatural, weaving a dark tale of love that transcends death. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quo porro excepturi doloribus dolorem dignissimos minus incidunt vel labore tempora commodi, quae ullam maxime expedita aspernatur totam possimus temporibus magni eum.Nihil laudantium voluptatum facere, voluptatem, nam illo harum dolorem repudiandae aut libero officiis! Quae ipsam nisi amet eius culpa magnam blanditiis labore sunt, tempore aliquid ad harum quam unde consequatur?",
    publishedYear: 1847,
    keywords: [
      "Emily Brontë",
      "Wuthering Heights",
      "gothic novel",
      "romance",
      "revenge",
      "passion",
      "haunting",
      "love",
      "tragedy",
      "nature",
      "social class",
      "obsession",
      "darkness",
      "19th century",
      "Yorkshire moors",
      "family",
      "ghosts",
      "soulmates",
      "classic literature",
      "brooding",
    ],
  },
  {
    title: "Great Expectations",
    author: "Charles Dickens",
    price: 990,
    image: "images/books/great-expectations.jpg",
    rating: {
      stars: 4.5,
      reviews: 1750,
    },
    genre: ["Classic", "Coming-of-Age"],
    copiesSold: 300,
    description:
      "Great Expectations is a coming-of-age story about an orphan named Pip who dreams of improving his social status. It explores themes of ambition, social class, love, and personal growth as Pip faces challenges and learns about loyalty, regret, and identity in Victorian England. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quo porro excepturi doloribus dolorem dignissimos minus incidunt vel labore tempora commodi, quae ullam maxime expedita aspernatur totam possimus temporibus magni eum.Nihil laudantium voluptatum facere, voluptatem, nam illo harum dolorem repudiandae aut libero officiis! Quae ipsam nisi amet eius culpa magnam blanditiis labore sunt, tempore aliquid ad harum quam unde consequatur?",
    publishedYear: 1861,
    keywords: [
      "Charles Dickens",
      "Great Expectations",
      "coming-of-age",
      "pip",
      "orphans",
      "social class",
      "ambition",
      "mystery",
      "redemption",
      "love",
      "wealth",
      "crime",
      "guilt",
      "identity",
      "19th century",
      "victorian england",
      "miss havisham",
      "estella",
      "classic literature",
      "personal growth",
    ],
  },
  {
    title: "Anna Karenina",
    author: "Leo Tolstoy",
    price: 1120,
    image: "images/books/anna-karenina.jpg",
    rating: {
      stars: 4.5,
      reviews: 2100,
    },
    genre: ["Classic", "Romance"],
    copiesSold: 4000,
    description:
      "Anna Karenina is a tragic tale of love and betrayal set in Russian high society. It follows the passionate affair between Anna and Count Vronsky, as well as the contrasting life of Levin, exploring themes of infidelity, family, social expectations, and the search for meaning in life. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quo porro excepturi doloribus dolorem dignissimos minus incidunt vel labore tempora commodi, quae ullam maxime expedita aspernatur totam possimus temporibus magni eum.Nihil laudantium voluptatum facere, voluptatem, nam illo harum dolorem repudiandae aut libero officiis! Quae ipsam nisi amet eius culpa magnam blanditiis labore sunt, tempore aliquid ad harum quam unde consequatur?",
    publishedYear: 1877,
    keywords: [
      "Leo Tolstoy",
      "Anna Karenina",
      "Russian literature",
      "love",
      "adultery",
      "tragic romance",
      "society",
      "marriage",
      "passion",
      "jealousy",
      "family",
      "moral dilemmas",
      "19th century",
      "social critique",
      "aristocracy",
      "psychological novel",
      "forbidden love",
      "class conflict",
      "tragic heroine",
      "realism",
    ],
  },
  {
    title: "Fahrenheit 451",
    author: "Ray Bradbury",
    price: 950,
    image: "images/books/fahrenheit-451.jpeg",
    rating: {
      stars: 4.5,
      reviews: 1420,
    },
    genre: ["Dystopian", "Science Fiction"],
    copiesSold: 300,
    description:
      "Fahrenheit 451 is set in a future society where books are outlawed and firemen burn any that are found. The story follows Guy Montag, a fireman who begins to question the purpose of his job and the oppressive regime he serves. As he discovers the power of literature and independent thought, Montag embarks on a dangerous journey toward freedom and self-discovery. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quo porro excepturi doloribus dolorem dignissimos minus incidunt vel labore tempora commodi, quae ullam maxime expedita aspernatur totam possimus temporibus magni eum.Nihil laudantium voluptatum facere, voluptatem, nam illo harum dolorem repudiandae aut libero officiis! Quae ipsam nisi amet eius culpa magnam blanditiis labore sunt, tempore aliquid ad harum quam unde consequatur?",
    publishedYear: 1953,
    keywords: [
      "Ray Bradbury",
      "Fahrenheit 451",
      "dystopia",
      "censorship",
      "book burning",
      "totalitarianism",
      "freedom of thought",
      "knowledge",
      "technology",
      "media control",
      "rebellion",
      "surveillance",
      "future society",
      "intellectualism",
      "anti-censorship",
      "mind control",
      "individualism",
      "firemen",
      "critical thinking",
      "conformity",
    ],
  },
  {
    title: "The Grapes of Wrath",
    author: "John Steinbeck",
    price: 980,
    image: "images/books/the-grapes-of-wrath.jpeg",
    rating: {
      stars: 4.5,
      reviews: 1320,
    },
    discount: 20,
    genre: ["Classic", "Historical Fiction"],
    copiesSold: 3000,
    description:
      "The Grapes of Wrath follows the Joad family as they journey from Oklahoma to California during the Great Depression, facing hardship, poverty, and injustice along the way. Steinbeck\u2019s novel paints a vivid portrait of resilience and the struggle for dignity in the face of overwhelming adversity. Through the family's eyes, readers witness the power of hope and the importance of community. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quo porro excepturi doloribus dolorem dignissimos minus incidunt vel labore tempora commodi, quae ullam maxime expedita aspernatur totam possimus temporibus magni eum.Nihil laudantium voluptatum facere, voluptatem, nam illo harum dolorem repudiandae aut libero officiis! Quae ipsam nisi amet eius culpa magnam blanditiis labore sunt, tempore aliquid ad harum quam unde consequatur?",
    publishedYear: 1939,
    keywords: [
      "John Steinbeck",
      "The Grapes of Wrath",
      "Great Depression",
      "Dust Bowl",
      "poverty",
      "migration",
      "family",
      "justice",
      "economic hardship",
      "resilience",
      "social injustice",
      "landowners",
      "farmers",
      "hope",
      "struggle",
      "American dream",
      "worker rights",
      "environmental disaster",
      "community",
      "survival",
    ],
  },
  {
    title: "Don Quixote",
    author: "Miguel de Cervantes",
    price: 1100,
    image: "images/books/don-quixote.jpeg",
    rating: {
      stars: 4.0,
      reviews: 980,
    },
    genre: ["Classic", "Adventure"],
    copiesSold: 2000,
    description:
      "Don Quixote tells the story of a man who, inspired by tales of chivalry, sets out on a quest to revive knighthood and right the world\u2019s wrongs. Accompanied by his loyal squire Sancho Panza, he embarks on a series of misadventures that blur the line between reality and imagination. The novel is a humorous and profound exploration of dreams, delusion, and the human spirit. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quo porro excepturi doloribus dolorem dignissimos minus incidunt vel labore tempora commodi, quae ullam maxime expedita aspernatur totam possimus temporibus magni eum.Nihil laudantium voluptatum facere, voluptatem, nam illo harum dolorem repudiandae aut libero officiis! Quae ipsam nisi amet eius culpa magnam blanditiis labore sunt, tempore aliquid ad harum quam unde consequatur?",
    publishedYear: 1605,
    keywords: [
      "Miguel de Cervantes",
      "Don Quixote",
      "chivalry",
      "knight-errant",
      "adventure",
      "illusion",
      "madness",
      "satire",
      "Spanish literature",
      "romance",
      "heroism",
      "idealism",
      "reality vs fantasy",
      "humor",
      "classics",
      "quest",
      "imagination",
      "love",
      "loyalty",
      "friendship",
    ],
  },
  {
    title: "The Redemption of Time",
    author: "Baoshu",
    price: 1150,
    image: "images/books/the-redemption-of-time.jpg",
    rating: {
      stars: 4.0,
      reviews: 800,
    },
    genre: ["Science Fiction"],
    copiesSold: 9000,
    description:
      "The Redemption of Time is an authorized sequel to Cixin Liu's Remembrance of Earth's Past trilogy, written by Baoshu. Expanding on the universe of the original series, the novel explores the fate of Yun Tianming and delves into cosmic mysteries, love, and sacrifice on a grand scale. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quo porro excepturi doloribus dolorem dignissimos minus incidunt vel labore tempora commodi, quae ullam maxime expedita aspernatur totam possimus temporibus magni eum.Nihil laudantium voluptatum facere, voluptatem, nam illo harum dolorem repudiandae aut libero officiis! Quae ipsam nisi amet eius culpa magnam blanditiis labore sunt, tempore aliquid ad harum quam unde consequatur?",
    publishedYear: 2011,
    keywords: [
      "Baoshu",
      "The Redemption of Time",
      "Three-Body Problem",
      "science fiction",
      "space opera",
      "cosmic",
      "time travel",
      "redemption",
      "philosophy",
      "fate",
      "multiverse",
      "technology",
      "alien contact",
      "future",
      "humanity",
      "survival",
      "ethics",
      "dark forest",
      "trilogy",
      "Chinese sci-fi",
    ],
  },
  {
    title: "Les Misérables",
    author: "Victor Hugo",
    price: 1200,
    image: "images/books/les-miserables.jpg",
    rating: {
      stars: 5.0,
      reviews: 2100,
    },
    genre: ["Classic", "Drama"],
    copiesSold: 3000,
    description:
      "Les Misérables chronicles the life of Jean Valjean, an ex-convict seeking redemption in 19th-century France. The novel explores themes of justice, love, and revolution, following a cast of unforgettable characters through triumph and tragedy. Hugo\u2019s masterpiece is a sweeping epic of human suffering and the quest for grace. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quo porro excepturi doloribus dolorem dignissimos minus incidunt vel labore tempora commodi, quae ullam maxime expedita aspernatur totam possimus temporibus magni eum.Nihil laudantium voluptatum facere, voluptatem, nam illo harum dolorem repudiandae aut libero officiis! Quae ipsam nisi amet eius culpa magnam blanditiis labore sunt, tempore aliquid ad harum quam unde consequatur?",
    publishedYear: 1862,
    keywords: [
      "Victor Hugo",
      "Les Misérables",
      "French literature",
      "revolution",
      "justice",
      "redemption",
      "poverty",
      "love",
      "sacrifice",
      "Paris",
      "19th century",
      "politics",
      "social inequality",
      "cosette",
      "valjean",
      "insurrection",
      "freedom",
      "humanity",
      "morality",
      "legacy",
    ],
  },
  {
    title: "The Picture of Dorian Gray",
    author: "Oscar Wilde",
    price: 930,
    image: "images/books/the-picture-of-dorian-gray.jpg",
    rating: {
      stars: 4.0,
      reviews: 1125,
    },
    discount: 10,
    genre: ["Classic", "Gothic"],
    copiesSold: 5000,
    description:
      "The Picture of Dorian Gray tells the story of a young man who remains eternally youthful while his portrait ages and records the consequences of his immoral actions. Wilde\u2019s only novel is a dark meditation on vanity, corruption, and the duality of human nature, filled with wit and philosophical insight. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quo porro excepturi doloribus dolorem dignissimos minus incidunt vel labore tempora commodi, quae ullam maxime expedita aspernatur totam possimus temporibus magni eum.Nihil laudantium voluptatum facere, voluptatem, nam illo harum dolorem repudiandae aut libero officiis! Quae ipsam nisi amet eius culpa magnam blanditiis labore sunt, tempore aliquid ad harum quam unde consequatur?",
    publishedYear: 1890,
    keywords: [
      "Oscar Wilde",
      "The Picture of Dorian Gray",
      "Gothic",
      "decadence",
      "vanity",
      "immortality",
      "corruption",
      "aestheticism",
      "morality",
      "sin",
      "youth",
      "portrait",
      "beauty",
      "hedonism",
      "duality",
      "London",
      "philosophy",
      "tragedy",
    ],
  },
  {
    title: "Middlemarch",
    author: "George Eliot",
    price: 1020,
    image: "images/books/middlemarch.jpeg",
    rating: {
      stars: 4.5,
      reviews: 980,
    },
    genre: ["Classic", "Literary Fiction"],
    copiesSold: 2000,
    description:
      "Middlemarch is a sweeping portrait of English provincial life in the 19th century, exploring the intersecting lives, ambitions, and disappointments of its richly drawn characters. The novel delves into themes of marriage, idealism, political reform, and personal growth, offering a profound meditation on the complexities of human nature and society. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quo porro excepturi doloribus dolorem dignissimos minus incidunt vel labore tempora commodi, quae ullam maxime expedita aspernatur totam possimus temporibus magni eum.Nihil laudantium voluptatum facere, voluptatem, nam illo harum dolorem repudiandae aut libero officiis! Quae ipsam nisi amet eius culpa magnam blanditiis labore sunt, tempore aliquid ad harum quam unde consequatur?",
    publishedYear: 1871,
    keywords: [
      "George Eliot",
      "Middlemarch",
      "Victorian",
      "social reform",
      "marriage",
      "morality",
      "ambition",
      "provincial life",
      "politics",
      "education",
      "love",
      "duty",
      "gender roles",
      "philosophy",
      "character study",
      "society",
      "intellect",
      "class",
    ],
  },
  {
    title: "The Brothers Karamazov",
    author: "Fyodor Dostoevsky",
    price: 1180,
    image: "images/books/the-brothers-karamazov.webp",
    rating: {
      stars: 5.0,
      reviews: 1650,
    },
    genre: ["Philosophical", "Psychological"],
    copiesSold: 7000,
    description:
      "The Brothers Karamazov is a philosophical masterpiece that explores faith, doubt, free will, and morality through the turbulent lives of three brothers and their father. Dostoevsky weaves a complex narrative of crime, passion, and redemption, challenging readers with deep questions about the human soul and the existence of God. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quo porro excepturi doloribus dolorem dignissimos minus incidunt vel labore tempora commodi, quae ullam maxime expedita aspernatur totam possimus temporibus magni eum.Nihil laudantium voluptatum facere, voluptatem, nam illo harum dolorem repudiandae aut libero officiis! Quae ipsam nisi amet eius culpa magnam blanditiis labore sunt, tempore aliquid ad harum quam unde consequatur?",
    publishedYear: 1880,
    keywords: [
      "Fyodor Dostoevsky",
      "The Brothers Karamazov",
      "Russian literature",
      "philosophy",
      "faith",
      "doubt",
      "morality",
      "family conflict",
      "crime",
      "justice",
      "redemption",
      "free will",
      "psychology",
      "existentialism",
      "sin",
      "love",
      "spirituality",
      "brotherhood",
    ],
  },
  {
    title: "Rebecca",
    author: "Daphne du Maurier",
    price: 940,
    image: "images/books/rebecca.webp",
    rating: {
      stars: 4.0,
      reviews: 1100,
    },
    discount: 12,
    genre: ["Gothic", "Mystery"],
    copiesSold: 3000,
    description:
      "Rebecca is a haunting tale of love and suspense set in the grand estate of Manderley, where a young bride is overshadowed by the lingering presence of her husband's first wife. The novel masterfully blends romance and psychological intrigue, unraveling secrets that threaten to destroy everything the heroine holds dear. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quo porro excepturi doloribus dolorem dignissimos minus incidunt vel labore tempora commodi, quae ullam maxime expedita aspernatur totam possimus temporibus magni eum.Nihil laudantium voluptatum facere, voluptatem, nam illo harum dolorem repudiandae aut libero officiis! Quae ipsam nisi amet eius culpa magnam blanditiis labore sunt, tempore aliquid ad harum quam unde consequatur?",
    publishedYear: 1938,
    keywords: [
      "Daphne du Maurier",
      "Rebecca",
      "gothic fiction",
      "mystery",
      "romance",
      "psychological thriller",
      "Manderley",
      "secrets",
      "identity",
      "obsession",
      "love",
      "jealousy",
      "haunting",
      "suspense",
      "first-person narrator",
      "marriage",
      "dark past",
    ],
  },
  {
    title: "The Sun Also Rises",
    author: "Ernest Hemingway",
    price: 970,
    image: "images/books/the-sun-also-rises.webp",
    rating: {
      stars: 4.0,
      reviews: 950,
    },
    genre: ["Classic", "Modernist"],
    copiesSold: 1200,
    description:
      "The Sun Also Rises follows a group of American and British expatriates as they travel from Paris to Spain in the 1920s, searching for meaning and excitement in the aftermath of World War I. Hemingway's spare prose captures the disillusionment and restless spirit of the Lost Generation, exploring themes of love, masculinity, and the pursuit of happiness. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quo porro excepturi doloribus dolorem dignissimos minus incidunt vel labore tempora commodi, quae ullam maxime expedita aspernatur totam possimus temporibus magni eum.Nihil laudantium voluptatum facere, voluptatem, nam illo harum dolorem repudiandae aut libero officiis! Quae ipsam nisi amet eius culpa magnam blanditiis labore sunt, tempore aliquid ad harum quam unde consequatur?",
    publishedYear: 1926,
    keywords: [
      "Ernest Hemingway",
      "The Sun Also Rises",
      "Lost Generation",
      "post-World War I",
      "expatriates",
      "disillusionment",
      "love",
      "friendship",
      "bullfighting",
      "Paris",
      "Spain",
      "identity",
      "aimlessness",
      "masculinity",
      "freedom",
      "jazz age",
    ],
  },
  {
    title: "The Count of Monte Cristo",
    author: "Alexandre Dumas",
    price: 1150,
    image: "images/books/the-count-of-monte-cristo.jpg",
    rating: {
      stars: 4.5,
      reviews: 1800,
    },
    genre: ["Adventure", "Historical Fiction"],
    copiesSold: 5000,
    description:
      "The Count of Monte Cristo is an epic tale of betrayal, revenge, and redemption, chronicling the transformation of Edmond Dantès from a wronged sailor into a mysterious and powerful nobleman. Set against the backdrop of post-Napoleonic France, the novel explores justice, fate, and the enduring power of hope. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quo porro excepturi doloribus dolorem dignissimos minus incidunt vel labore tempora commodi, quae ullam maxime expedita aspernatur totam possimus temporibus magni eum.Nihil laudantium voluptatum facere, voluptatem, nam illo harum dolorem repudiandae aut libero officiis! Quae ipsam nisi amet eius culpa magnam blanditiis labore sunt, tempore aliquid ad harum quam unde consequatur?",
    publishedYear: 1844,
    keywords: [
      "The Count of Monte Cristo",
      "Alexandre Dumas",
      "adventure",
      "revenge",
      "justice",
      "betrayal",
      "forgiveness",
      "adventure",
      "imprisonment",
      "escape",
      "mystery",
      "love",
      "wealth",
      "identity",
      "redemption",
      "19th century",
      "French literature",
      "justice",
    ],
  },
  {
    title: "Persuasion",
    author: "Jane Austen",
    price: 940,
    image: "images/books/persuasion.jpg",
    rating: {
      stars: 4.5,
      reviews: 890,
    },
    genre: ["Classic", "Romance"],
    copiesSold: 1500,
    description:
      "Persuasion tells the story of Anne Elliot, a woman who is given a second chance at love when Captain Wentworth reenters her life after many years. Set in Regency England, the novel explores themes of regret, social pressure, and the enduring power of true affection. Austen\u2019s final completed work is celebrated for its mature insight and emotional depth. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quo porro excepturi doloribus dolorem dignissimos minus incidunt vel labore tempora commodi, quae ullam maxime expedita aspernatur totam possimus temporibus magni eum.Nihil laudantium voluptatum facere, voluptatem, nam illo harum dolorem repudiandae aut libero officiis! Quae ipsam nisi amet eius culpa magnam blanditiis labore sunt, tempore aliquid ad harum quam unde consequatur?",
    publishedYear: 1817,
    keywords: [
      "Jane Austen",
      "Persuasion",
      "romance",
      "regret",
      "second chances",
      "social class",
      "love",
      "persuasion",
      "family",
      "19th century",
      "English literature",
      "marriage",
      "emotions",
      "character growth",
    ],
  },
  {
    title: "The Secret Garden",
    author: "Frances Hodgson Burnett",
    price: 860,
    image: "images/books/the-secret-garden.webp",
    rating: {
      stars: 4.0,
      reviews: 1050,
    },
    genre: ["Classic", "Children's Literature"],
    copiesSold: 1200,
    description:
      "The Secret Garden follows Mary Lennox, a lonely orphan who discovers a hidden, neglected garden on her uncle\u2019s estate. As she brings the garden back to life, Mary\u2019s own world transforms, and she forms deep friendships that help her heal. The novel is a timeless tale of renewal, friendship, and the magic of nature. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quo porro excepturi doloribus dolorem dignissimos minus incidunt vel labore tempora commodi, quae ullam maxime expedita aspernatur totam possimus temporibus magni eum.Nihil laudantium voluptatum facere, voluptatem, nam illo harum dolorem repudiandae aut libero officiis! Quae ipsam nisi amet eius culpa magnam blanditiis labore sunt, tempore aliquid ad harum quam unde consequatur?",
    publishedYear: 1911,
    keywords: [
      "Frances Hodgson Burnett",
      "The Secret Garden",
      "children's literature",
      "friendship",
      "healing",
      "nature",
      "mystery",
      "growth",
      "garden",
      "magic",
      "family",
      "recovery",
      "hope",
      "transformation",
    ],
  },
  {
    title: "Siddhartha",
    author: "Hermann Hesse",
    price: 900,
    image: "images/books/siddhartha.jpg",
    rating: {
      stars: 4.0,
      reviews: 970,
    },
    genre: ["Philosophical", "Spiritual"],
    copiesSold: 1500,
    description:
      "Siddhartha traces the spiritual journey of a young man in ancient India as he seeks enlightenment and self-discovery. Through encounters with wealth, love, and asceticism, Siddhartha learns that true wisdom comes from experience and inner peace. Hesse\u2019s novel is a profound meditation on the nature of happiness and fulfillment. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quo porro excepturi doloribus dolorem dignissimos minus incidunt vel labore tempora commodi, quae ullam maxime expedita aspernatur totam possimus temporibus magni eum.Nihil laudantium voluptatum facere, voluptatem, nam illo harum dolorem repudiandae aut libero officiis! Quae ipsam nisi amet eius culpa magnam blanditiis labore sunt, tempore aliquid ad harum quam unde consequatur?",
    publishedYear: 1922,
    keywords: [
      "Hermann Hesse",
      "Siddhartha",
      "spirituality",
      "self-discovery",
      "enlightenment",
      "Buddhism",
      "philosophy",
      "journey",
      "meditation",
      "inner peace",
      "wisdom",
      "awakening",
      "nature",
      "existentialism",
    ],
  },
  {
    title: "The Old Man and the Sea",
    author: "Ernest Hemingway",
    price: 880,
    image: "images/books/the-old-man-and-the-sea.jpg",
    rating: {
      stars: 4.0,
      reviews: 1120,
    },
    genre: ["Classic", "Adventure"],
    copiesSold: 2500,
    description:
      "The Old Man and the Sea tells the story of Santiago, an aging Cuban fisherman who struggles to catch a giant marlin after a long run of bad luck. The novella explores themes of perseverance, dignity, and the relationship between humans and nature. Hemingway\u2019s simple yet powerful prose earned him the Pulitzer Prize for this work. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quo porro excepturi doloribus dolorem dignissimos minus incidunt vel labore tempora commodi, quae ullam maxime expedita aspernatur totam possimus temporibus magni eum.Nihil laudantium voluptatum facere, voluptatem, nam illo harum dolorem repudiandae aut libero officiis! Quae ipsam nisi amet eius culpa magnam blanditiis labore sunt, tempore aliquid ad harum quam unde consequatur?",
    publishedYear: 1952,
    keywords: [
      "Ernest Hemingway",
      "The Old Man and the Sea",
      "struggle",
      "perseverance",
      "nature",
      "fishing",
      "isolation",
      "man vs nature",
      "endurance",
      "hope",
      "courage",
      "loneliness",
      "survival",
      "heroism",
      "determination",
      "aging",
      "fate",
      "resilience",
      "human spirit",
      "sea",
      "santiago",
    ],
  },
  {
    title: "Madame Bovary",
    author: "Gustave Flaubert",
    price: 970,
    image: "images/books/madame-bovary.jpg",
    rating: {
      stars: 4.0,
      reviews: 990,
    },
    genre: ["Classic", "Literary Fiction"],
    copiesSold: 600,
    description:
      "Madame Bovary follows Emma Bovary, a doctor's wife who seeks escape from her provincial life through romantic fantasies and reckless spending. Flaubert\u2019s masterpiece is a critical exploration of desire, disillusionment, and the constraints of society. The novel is renowned for its realism and psychological insight. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quo porro excepturi doloribus dolorem dignissimos minus incidunt vel labore tempora commodi, quae ullam maxime expedita aspernatur totam possimus temporibus magni eum.Nihil laudantium voluptatum facere, voluptatem, nam illo harum dolorem repudiandae aut libero officiis! Quae ipsam nisi amet eius culpa magnam blanditiis labore sunt, tempore aliquid ad harum quam unde consequatur?",
    publishedYear: 1856,
    keywords: [
      "Madame Bovary",
      "Gustave Flaubert",
      "romanticism",
      "realism",
      "adultery",
      "boredom",
      "illusion",
      "discontent",
      "marriage",
      "passion",
      "social criticism",
      "provincial life",
      "tragedy",
      "desire",
      "materialism",
      "frustration",
      "feminine struggle",
      "escape",
      "identity",
      "melancholy",
    ],
  },
  {
    title: "The Call of the Wild",
    author: "Jack London",
    price: 860,
    image: "images/books/the-call-of-the-wild.jpg",
    rating: {
      stars: 4.0,
      reviews: 1020,
    },
    discount: 7,
    genre: ["Adventure", "Classic"],
    copiesSold: 800,
    description:
      "The Call of the Wild follows Buck, a domesticated dog who is stolen from his home and sold into the brutal life of an Alaskan sled dog. As Buck adapts to the harsh wilderness, he discovers his primal instincts and the call of his wild ancestry. London's novel explores survival, transformation, and the enduring power of nature. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quo porro excepturi doloribus dolorem dignissimos minus incidunt vel labore tempora commodi, quae ullam maxime expedita aspernatur totam possimus temporibus magni eum.Nihil laudantium voluptatum facere, voluptatem, nam illo harum dolorem repudiandae aut libero officiis! Quae ipsam nisi amet eius culpa magnam blanditiis labore sunt, tempore aliquid ad harum quam unde consequatur?",
    publishedYear: 1903,
    keywords: [
      "The Call of the Wild",
      "Jack London",
      "adventure",
      "survival",
      "nature",
      "wilderness",
      "dog",
      "Alaska",
      "gold rush",
      "instinct",
      "animal behavior",
      "harsh environment",
      "loyalty",
      "freedom",
      "transformation",
      "primitive",
      "struggle",
      "man vs nature",
      "resilience",
      "leadership",
    ],
  },
  {
    title: "The Three-Body Problem",
    author: "Cixin Liu",
    price: 1100,
    image: "images/books/the-three-body-problem.jpg",
    rating: {
      stars: 4.5,
      reviews: 1600,
    },
    genre: ["Science Fiction"],
    copiesSold: 15000,
    description:
      "The Three-Body Problem is the first volume of Cixin Liu's Remembrance of Earth's Past trilogy. The novel explores humanity's first contact with an alien civilization, set against the backdrop of China's Cultural Revolution and a mysterious virtual reality game. It delves into physics, philosophy, and the fate of civilizations.Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quo porro excepturi doloribus dolorem dignissimos minus incidunt vel labore tempora commodi, quae ullam maxime expedita aspernatur totam possimus temporibus magni eum.Nihil laudantium voluptatum facere, voluptatem, nam illo harum dolorem repudiandae aut libero officiis! Quae ipsam nisi amet eius culpa magnam blanditiis labore sunt, tempore aliquid ad harum quam unde consequatur?",
    publishedYear: 2008,
    keywords: [
      "The Three-Body Problem",
      "Liu Cixin",
      "science fiction",
      "hard sci-fi",
      "extraterrestrial",
      "alien invasion",
      "physics",
      "civilization",
      "cultural revolution",
      "virtual reality",
      "quantum physics",
      "space",
      "cosmos",
      "technology",
      "first contact",
      "astrophysics",
      "philosophy",
      "survival",
      "humanity",
      "mathematics",
    ],
  },
  {
    title: "A Room with a View",
    author: "E.M. Forster",
    price: 880,
    image: "images/books/a-room-with-a-view.webp",
    rating: {
      stars: 4.0,
      reviews: 950,
    },
    genre: ["Classic", "Romance"],
    copiesSold: 600,
    description:
      "A Room with a View tells the story of Lucy Honeychurch, a young Englishwoman who finds herself torn between convention and passion during a trip to Italy. As she navigates love, societal expectations, and self-discovery, Lucy must choose between a safe engagement and a life of authenticity. Forster's novel is a witty and insightful exploration of Edwardian society. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quo porro excepturi doloribus dolorem dignissimos minus incidunt vel labore tempora commodi, quae ullam maxime expedita aspernatur totam possimus temporibus magni eum.Nihil laudantium voluptatum facere, voluptatem, nam illo harum dolorem repudiandae aut libero officiis! Quae ipsam nisi amet eius culpa magnam blanditiis labore sunt, tempore aliquid ad harum quam unde consequatur?",
    publishedYear: 1908,
    keywords: [
      "A Room with a View",
      "E.M. Forster",
      "Edwardian era",
      "romance",
      "social class",
      "England",
      "Italy",
      "self-discovery",
      "love",
      "society",
      "individuality",
      "convention",
      "travel",
      "awakening",
      "courtship",
      "Victorian values",
      "freedom",
      "coming of age",
      "conflict",
      "identity",
    ],
  },
  {
    title: "The Stranger",
    author: "Albert Camus",
    price: 920,
    image: "images/books/the-stranger.jpg",
    rating: {
      stars: 4.0,
      reviews: 1200,
    },
    genre: ["Philosophical", "Existential"],
    copiesSold: 7000,
    description:
      "The Stranger centers on Meursault, an emotionally detached French Algerian who commits a senseless murder. Through his trial and reflections, Camus explores themes of absurdity, alienation, and the search for meaning in a seemingly indifferent universe. The novel is a cornerstone of existentialist literature. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quo porro excepturi doloribus dolorem dignissimos minus incidunt vel labore tempora commodi, quae ullam maxime expedita aspernatur totam possimus temporibus magni eum.Nihil laudantium voluptatum facere, voluptatem, nam illo harum dolorem repudiandae aut libero officiis! Quae ipsam nisi amet eius culpa magnam blanditiis labore sunt, tempore aliquid ad harum quam unde consequatur?",
    publishedYear: 1942,
    keywords: [
      "the stranger",
      "stranger",
      "albert camus",
      "camus",
      "meursault",
      "philosophical",
      "existential",
      "existentialism",
      "absurdism",
      "alienation",
      "absurdity",
      "french algerian",
      "trial",
      "detachment",
      "meaning",
      "indifference",
      "1942",
    ],
  },
  {
    title: "The Wind in the Willows",
    author: "Kenneth Grahame",
    price: 870,
    image: "images/books/the-wind-in-the-willows.jpg",
    rating: {
      stars: 4.5,
      reviews: 1100,
    },
    genre: ["Classic", "Children's Literature"],
    copiesSold: 1500,
    description:
      "The Wind in the Willows follows the adventures of Mole, Rat, Toad, and Badger along the riverbank and in the English countryside. The novel blends whimsical escapades with gentle reflections on friendship, home, and the joys of nature. Grahame's beloved tale is cherished for its warmth and imaginative storytelling. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quo porro excepturi doloribus dolorem dignissimos minus incidunt vel labore tempora commodi, quae ullam maxime expedita aspernatur totam possimus temporibus magni eum.Nihil laudantium voluptatum facere, voluptatem, nam illo harum dolorem repudiandae aut libero officiis! Quae ipsam nisi amet eius culpa magnam blanditiis labore sunt, tempore aliquid ad harum quam unde consequatur?",
    publishedYear: 1908,
    keywords: [
      "The Wind in the Willows",
      "Kenneth Grahame",
      "friendship",
      "adventure",
      "nature",
      "riverbank",
      "mole",
      "ratty",
      "toad",
      "badger",
      "animal characters",
      "English countryside",
      "loyalty",
      "home",
      "escape",
      "nostalgia",
      "whimsy",
      "coming of age",
      "seasons",
      "exploration",
    ],
  },
  {
    title: "Death's End",
    author: "Cixin Liu",
    price: 1200,
    image: "images/books/deaths-end.jpg",
    rating: {
      stars: 4.5,
      reviews: 1400,
    },
    genre: ["Science Fiction"],
    copiesSold: 15000,
    description:
      "Death's End is the third and final volume of Cixin Liu's Remembrance of Earth's Past trilogy. The novel follows humanity's struggle for survival as cosmic threats escalate, exploring advanced science, interstellar war, and the ultimate fate of the universe.Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quo porro excepturi doloribus dolorem dignissimos minus incidunt vel labore tempora commodi, quae ullam maxime expedita aspernatur totam possimus temporibus magni eum.Nihil laudantium voluptatum facere, voluptatem, nam illo harum dolorem repudiandae aut libero officiis! Quae ipsam nisi amet eius culpa magnam blanditiis labore sunt, tempore aliquid ad harum quam unde consequatur?",
    publishedYear: 2010,
    keywords: [
      "Death's End",
      "Cixin Liu",
      "science fiction",
      "space opera",
      "cosmic civilization",
      "dark forest theory",
      "advanced technology",
      "interstellar conflict",
      "human survival",
      "time dilation",
      "alien invasion",
      "multidimensional",
      "futuristic",
      "philosophy",
      "physics",
      "space exploration",
      "trilogy conclusion",
      "cosmic horror",
      "suspense",
      "hard sci-fi",
    ],
  },
  {
    title: "David Copperfield",
    author: "Charles Dickens",
    price: 990,
    image: "images/books/david-copperfield.jpg",
    rating: {
      stars: 4.5,
      reviews: 1300,
    },
    genre: ["Classic", "Coming-of-Age"],
    copiesSold: 2500,
    description:
      "David Copperfield traces the life of its titular character from childhood adversity to adult success as a writer. Along the way, David encounters a memorable cast of friends and villains, navigating love, loss, and personal growth. Dickens\u2019s semi-autobiographical novel is celebrated for its vivid storytelling and insight into Victorian society. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quo porro excepturi doloribus dolorem dignissimos minus incidunt vel labore tempora commodi, quae ullam maxime expedita aspernatur totam possimus temporibus magni eum.Nihil laudantium voluptatum facere, voluptatem, nam illo harum dolorem repudiandae aut libero officiis! Quae ipsam nisi amet eius culpa magnam blanditiis labore sunt, tempore aliquid ad harum quam unde consequatur?",
    publishedYear: 1850,
    keywords: [
      "David Copperfield",
      "Charles Dickens",
      "coming-of-age",
      "victorian era",
      "orphan",
      "personal growth",
      "social class",
      "friendship",
      "love",
      "perseverance",
      "adventure",
      "family",
      "hardship",
      "literary classic",
      "memoir style",
      "England",
      "childhood",
      "education",
      "workplace",
      "romance",
    ],
  },
  {
    title: "The Metamorphosis",
    author: "Franz Kafka",
    price: 910,
    image: "images/books/the-metamorphosis.jpg",
    rating: {
      stars: 4.0,
      reviews: 1050,
    },
    discount: 13,
    genre: ["Classic", "Absurdist"],
    copiesSold: 1500,
    description:
      "The Metamorphosis tells the surreal story of Gregor Samsa, who wakes up one morning to find himself transformed into a giant insect. As Gregor and his family struggle to cope with his new condition, Kafka explores themes of alienation, identity, and the absurdity of existence. The novella is a landmark of modernist literature. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quo porro excepturi doloribus dolorem dignissimos minus incidunt vel labore tempora commodi, quae ullam maxime expedita aspernatur totam possimus temporibus magni eum.Nihil laudantium voluptatum facere, voluptatem, nam illo harum dolorem repudiandae aut libero officiis! Quae ipsam nisi amet eius culpa magnam blanditiis labore sunt, tempore aliquid ad harum quam unde consequatur?",
    publishedYear: 1915,
    keywords: [
      "The Metamorphosis",
      "Franz Kafka",
      "absurdism",
      "alienation",
      "transformation",
      "existentialism",
      "family conflict",
      "identity",
      "isolation",
      "surrealism",
      "insect",
      "absurd",
      "guilt",
      "sacrifice",
      "psychological",
      "modernist literature",
      "20th century",
      "novella",
      "symbolism",
      "bureaucracy",
    ],
  },
  {
    title: "The Odyssey",
    author: "Homer",
    price: 1100,
    image: "images/books/the-odyssey.jpeg",
    rating: {
      stars: 4.5,
      reviews: 1700,
    },
    genre: ["Epic", "Classic"],
    copiesSold: 5000,
    description:
      "The Odyssey is an ancient Greek epic poem that recounts the adventures of Odysseus as he struggles to return home after the Trojan War. Facing mythical creatures, divine wrath, and countless obstacles, Odysseus\u2019s journey is a timeless tale of perseverance, cunning, and the enduring power of home and family. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quo porro excepturi doloribus dolorem dignissimos minus incidunt vel labore tempora commodi, quae ullam maxime expedita aspernatur totam possimus temporibus magni eum.Nihil laudantium voluptatum facere, voluptatem, nam illo harum dolorem repudiandae aut libero officiis! Quae ipsam nisi amet eius culpa magnam blanditiis labore sunt, tempore aliquid ad harum quam unde consequatur?",
    publishedYear: -800,
    keywords: [
      "The Odyssey",
      "Homer",
      "epic poem",
      "ancient Greece",
      "adventure",
      "heroism",
      "Odysseus",
      "journey",
      "mythology",
      "war",
      "homecoming",
      "sea voyage",
      "gods",
      "fate",
      "loyalty",
      "temptation",
      "Cicones",
      "Cyclops",
      "Circe",
      "Penelope",
      "Ithaca",
      "Odyssey themes",
      "Greek epic",
      "Odyssey characters",
    ],
  },
  {
    title: "The Bell Jar",
    author: "Sylvia Plath",
    price: 950,
    image: "images/books/the-bell-jar.webp",
    rating: {
      stars: 4.0,
      reviews: 1250,
    },
    genre: ["Classic", "Psychological Fiction"],
    copiesSold: 1500,
    description:
      "The Bell Jar follows Esther Greenwood, a young woman whose promising life unravels as she descends into mental illness. Plath\u2019s only novel offers a raw and intimate portrayal of depression, identity, and the pressures faced by women in the 1950s. The book is acclaimed for its lyrical prose and emotional honesty. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quo porro excepturi doloribus dolorem dignissimos minus incidunt vel labore tempora commodi, quae ullam maxime expedita aspernatur totam possimus temporibus magni eum.Nihil laudantium voluptatum facere, voluptatem, nam illo harum dolorem repudiandae aut libero officiis! Quae ipsam nisi amet eius culpa magnam blanditiis labore sunt, tempore aliquid ad harum quam unde consequatur?",
    publishedYear: 1963,
    keywords: [
      "The Bell Jar",
      "Sylvia Plath",
      "mental health",
      "depression",
      "coming-of-age",
      "identity",
      "female protagonist",
      "psychological fiction",
      "suicide",
      "society",
      "alienation",
      "struggle",
      "American literature",
      "autobiographical",
      "1960s",
      "existential crisis",
      "self-discovery",
      "St. Vincent's Hospital",
      "New York City",
      "poetry",
    ],
  },
  {
    title: "The Three Musketeers",
    author: "Alexandre Dumas",
    price: 990,
    image: "images/books/the-three-musketeers.jpg",
    rating: {
      stars: 4.5,
      reviews: 1250,
    },
    genre: ["Adventure", "Historical Fiction"],
    copiesSold: 5000,
    copiesSold: 2567,
    description:
      "The Three Musketeers follows the adventures of d'Artagnan and his three musketeer friends as they fight for justice and honor in 17th-century France. The novel is filled with intrigue, romance, and swashbuckling action. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quo porro excepturi doloribus dolorem dignissimos minus incidunt vel labore tempora commodi, quae ullam maxime expedita aspernatur totam possimus temporibus magni eum.Nihil laudantium voluptatum facere, voluptatem, nam illo harum dolorem repudiandae aut libero officiis! Quae ipsam nisi amet eius culpa magnam blanditiis labore sunt, tempore aliquid ad harum quam unde consequatur?",
    publishedYear: 1844,
    keywords: [
      "The Three Musketeers",
      "Alexandre Dumas",
      "adventure",
      "historical fiction",
      "swashbuckling",
      "friendship",
      "honor",
      "loyalty",
      "duels",
      "17th century",
      "France",
      "King Louis XIII",
      "Cardinal Richelieu",
      "d'Artagnan",
      "Athos",
      "Porthos",
      "Aramis",
      "romance",
      "political intrigue",
      "musketeers",
      "courage",
      "action",
    ],
  },
  {
    title: "East of Eden",
    author: "John Steinbeck",
    price: 1050,
    image: "images/books/east-of-eden.jpg",
    rating: {
      stars: 4.5,
      reviews: 1100,
    },
    genre: ["Classic", "Family Saga"],
    copiesSold: 3500,
    description:
      "East of Eden is a sweeping family saga set in California's Salinas Valley, exploring themes of good and evil, love, and the struggle for acceptance across generations. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quo porro excepturi doloribus dolorem dignissimos minus incidunt vel labore tempora commodi, quae ullam maxime expedita aspernatur totam possimus temporibus magni eum.Nihil laudantium voluptatum facere, voluptatem, nam illo harum dolorem repudiandae aut libero officiis! Quae ipsam nisi amet eius culpa magnam blanditiis labore sunt, tempore aliquid ad harum quam unde consequatur?",
    publishedYear: 1952,
    keywords: [
      "East of Eden",
      "John Steinbeck",
      "family saga",
      "good vs evil",
      "Cain and Abel",
      "California",
      "Salinas Valley",
      "generations",
      "brotherhood",
      "inheritance",
      "morality",
      "identity",
      "love",
      "betrayal",
      "redemption",
      "coming-of-age",
      "ranching",
      "human nature",
      "struggle",
      "hope",
      "darkness",
    ],
  },
  {
    title: "The Dark Forest",
    author: "Cixin Liu",
    price: 1150,
    image: "images/books/the-dark-forest.jpg",
    rating: {
      stars: 4.5,
      reviews: 1350,
    },
    genre: ["Science Fiction"],
    copiesSold: 17000,
    discount: 11,
    description:
      "The Dark Forest is the second book in Cixin Liu's Remembrance of Earth's Past trilogy. As humanity faces an impending alien invasion, the world must unite and confront the cosmic threat using both science and strategy. The novel explores the concept of cosmic sociology, the 'dark forest' theory, and the survival instincts of civilizations in the universe. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quo porro excepturi doloribus dolorem dignissimos minus incidunt vel labore tempora commodi, quae ullam maxime expedita aspernatur totam possimus temporibus magni eum.Nihil laudantium voluptatum facere, voluptatem, nam illo harum dolorem repudiandae aut libero officiis! Quae ipsam nisi amet eius culpa magnam blanditiis labore sunt, tempore aliquid ad harum quam unde consequatur?",
    publishedYear: 2008,
    keywords: [
      "The Dark Forest",
      "Liu Cixin",
      "science fiction",
      "hard sci-fi",
      "space opera",
      "cosmic civilization",
      "extraterrestrial",
      "alien invasion",
      "dark forest theory",
      "survival",
      "strategy",
      "first contact",
      "humanity",
      "politics",
      "technology",
      "future",
      "trilogy",
      "Three-Body Problem",
      "astrophysics",
      "philosophy",
      "dystopia",
    ],
  },
];
